set (CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} -DTARGET_OS_MAC=1")

if(NOT DISABLE_NEWLINE_EOF_CHECK)
  set (CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} -Wnewline-eof")
endif()

set (CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} -Wshadow")
