#!/bin/sh

if [ "$#" -lt 2 ]; then
        echo "Usage $0: lib_location install_location"
	exit
fi

MSGPACK_LIB_LOCATION=$1
MSGPACK_INSTALL_LIB_LOCATION=$2
MSGPACK_SRC_LOCATION=$3
MSGPACK_INSTALL_INCLUDE_LOCATION="$MSGPACK_INSTALL_LIB_LOCATION/../../include"

echo $MSGPACK_SRC_LOCATION ;
echo "$(pwd)$MSGPACK_SRC_LOCATION/src/msgpack/*" ;

# Cleanup gmock install sandbox
rm -rf "$MSGPACK_INSTALL_LIB_LOCATION"
rm -rf "$MSGPACK_INSTALL_INCLUDE_LOCATION"

mkdir -p "$MSGPACK_INSTALL_LIB_LOCATION"
mkdir -p "$MSGPACK_INSTALL_INCLUDE_LOCATION"

# Install gmock
cp "$MSGPACK_LIB_LOCATION/libmsgpack.a" "$MSGPACK_INSTALL_LIB_LOCATION"
cp "$MSGPACK_LIB_LOCATION/src/msgpack/version.h" "$MSGPACK_INSTALL_INCLUDE_LOCATION"
cp -R $(pwd)/$MSGPACK_SRC_LOCATION/src/msgpack/* "$MSGPACK_INSTALL_INCLUDE_LOCATION"
